# Browser configuration
browser=chromium
headless=true
slowMo=0

# Application
baseUrl=http://localhost:5173

# Timeouts
timeout=3000
navigationTimeout=3000

#Execution
screenshotOnFailure=true
traceOnFailure=true
videoRecording=false

